name: Update Philoberry Infrastructure

on:
  repository_dispatch:
    types: [update-infrastructure]

env:
  AWS_REGION: ap-northeast-2
  ECS_SERVICE: staging
  ECS_CLUSTER: philoberry-ecs-cluster
  ECS_TD: ../ecs-service/service.config.json.tpl

jobs:
  update_service:
    runs-on: ubuntu-latest
    name: Update ECS Service
    steps:

      - name: Checkout code 
        uses: actions/checkout@v2 

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name : Deploy Amazon ECS task definition  
        uses : aws-actions/amazon-ecs-deploy-task-definition@v1   
        with :
          task-definition : ${{ env.ECS_TD }}
          service : ${{ env.ECS_SERVICE }}
          cluster : ${{ env.ECS_CLUSTER }}
          wait-for-service-stability:true